apiVersion: apps/v1
kind: Deployment
metadata:
  name: english-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: english-client
  template:
    metadata:
      labels:
        app: english-client
    spec:
      containers:
        - name: english-client
          image: example/englishclient:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3100
          env:
            - name: eureka.client.serviceUrl.defaultZone
              value: http://discovery-service:8761/eureka/
            - name: services.client
              value: spanish-client
            # - name: EUREKA_SERVER_URL
            #   valueFrom:
            #     configMapKeyRef:
            #     # name of the config map
            #       name: eureka-client-config
            #       key: application.yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spanish-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spanish-client
  template:
    metadata:
      labels:
        app: spanish-client
    spec:
      containers:
        - name: spanish-client
          image: example/spanishclient:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3200
          env:
            - name: eureka.client.serviceUrl.defaultZone
              value: http://discovery-service:8761/eureka/
            - name: services.client
              value: english-client
            # - name: EUREKA_SERVER_URL
            #   valueFrom:
            #     configMapKeyRef:
            #     # name of the config map
            #       name: eureka-client-config
            #       key: application.yml                      
---
apiVersion: v1
kind: Service
metadata:
  name: english-client
spec:
  selector:
    app: english-client
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
---
apiVersion: v1
kind: Service
metadata:
  name: spanish-client
spec:
  selector:
    app: spanish-client
  ports:
    - protocol: TCP
      port: 3200
      targetPort: 3200      